package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.AccountStatus;

public class AccountStatusWritingConverter extends AbstractPostgresEnumWritingConverter<AccountStatus>{}