package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ModerationAction;

public class ModerationActionWritingConverter extends AbstractPostgresEnumWritingConverter<ModerationAction>{}