package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ReactionType;

public class ReactionTypeWritingConverter extends AbstractPostgresEnumWritingConverter<ReactionType>{}