package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ReportTargetType;

public class ReportTargetTypeWritingConverter extends AbstractPostgresEnumWritingConverter<ReportTargetType>{}