package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ReportCategory;

public class ReportCategoryWritingConverter extends AbstractPostgresEnumWritingConverter<ReportCategory>{}