package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ThreadStatus;

public class ThreadStatusWritingConverter extends AbstractPostgresEnumWritingConverter<ThreadStatus>{}