package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.ThreadType;

public class ThreadTypeWritingConverter extends AbstractPostgresEnumWritingConverter<ThreadType>{}