package com.mentalhealthforum.mentalhealthforum_backend.config.r2dbcConverters;

import com.mentalhealthforum.mentalhealthforum_backend.enums.UserAuditReasonKey;

public class UserAuditReasonKeyWritingConverter extends AbstractPostgresEnumWritingConverter<UserAuditReasonKey>{}